### PR TITLE
Update README.md with more Pyenv for all OS

### PR DESCRIPTION
**Pull request by meramsey**
Update README.md with more clear Pyenv install for all OS

Its a little tricky sometimes hunting down all the exact steps to get started with pyenv so added steps for all OS's

This also does a nice spoiler for each OS

Screenshot from 2022-02-25 10-23-45

Screenshot from 2022-02-25 10-23-58

### CODE REVIEW

**Comment by pawamoy** [comment]
This feels like *a lot* of contents for a tool that is not even mandatory to use. Honestly I'd rather remove the pyenv section entirely if it's not complete enough. Devs can still add such documentation to CONTRIBUTING themselves. Keep in mind such docs have to be *maintained* over time (tools change, systems change, versions change, etc.). Are you willing to bear that yourself? I'm not :smile: 

In fact, I documented pyenv at first because Python 3.6 was recent, but now my projects just follow Python versions life-cycles, i.e. minimum required version is last EOL + 1. It means that the minimum required version should be easily available to anyone on modern systems, and therefore we don't even have to show a way to install that version.

What do you think?

**Comment by meramsey** [comment]
I guess it makes sense. I mostly felt like if having directions to it for just Linux makes it scary for those on Windows or Mac to bother trying to translate them via the other projects so I kinda figured might as well have it for all. 

I don't think the underlying guide would really drift that much but i totally see your point. 

The spoiler's does make it more manageable but i suppose one could see it as being unnecessary. 

I do like the idea of maybe having it as its own thing possibly for those without it preinstalled cause then it wouldn't clutter things in the Contributing or main section maybe just a local repo link to the InstallPython.md or something maybe. If that is something we can include until it doesn't make sense in its own .md file could be best of both worlds I think information is there if needed or if someone doesn't need it just delete that one file from their project and the line referencing it.

**Comment by pawamoy** [comment]
So, what do we do here :sweat_smile:? The thing is, I don't use this template anymore, so I tell myself "why not letting the community manage it". But so far there has not been a lot of contributors, and I don't want a single contributor to choose the direction the project is taking. I also don't want to spend too much time maintaining it.

So my opinion here is: we should just remove the pyenv paragraph from the generated readme. Less maintenance, less ambiguous installation instructions. After all, "how to install Python" is not quite in the scope of this project. And if you feel these docs are still very important to have, then maybe you should improve pyenv's installation instructions in its own readme?

**Comment by meramsey** [comment]
You make a valid point. Closing this now ;)

As much as I want to get PDM as my new default most of my personal and few work ones are on the poetry setup and working well. Last time I tried PDM had some weird stuff going on. I really need to give it another chance cause I love the copier duties combo its really nice.

Also on that note there is a nice new tool i think kinda augments both poetry/pdm PyProjectx
https://upcycled-code.com/blog/plug-and-play-python-development/
https://github.com/houbie/pyprojectx

I tried out with one of my copier poetry projects and its pretty sweet hoping to do that for rest of my projects cause it makes getting up to speed super easy.
https://github.com/meramsey/wizardwebssh/blob/master/pyproject.toml#L73-L141

**Comment by pawamoy** [comment]
Yeah pyprojectx has some compelling arguments :slightly_smiling_face: 

Closing then! You can send a new PR to remove the pyenv section if you want.

**Pull request closed without merging**
